### ISSUE TITLE
MVC 5?

### ISSUE THREAD

**Issue by Booster2ooo** [SparkViewEngine/spark#50]
Is there any version of Spark supporting MVC 5 planned ?

**Comment by RobertTheGrey** [comment]
Deployed to Nuget [Spark.Web.Mvc5](https://www.nuget.org/packages/Spark.Web.Mvc5/)

**Comment by Booster2ooo** [comment]
Thanks Robert. 
It's too bad Spark is slowly going unmaintained due to the lack of official support. Now, even your domain name is squatted, it's almost impossible to find the documentation. It's kind of sad when a good idea dies like this.

**Comment by RobertTheGrey** [comment]
Thanks - yeah unfortunately I had no control over the domain and nobody is prepared to pay money for the project to keep the domain going. So now everything is on github and the documentation is there as well. We cannot stop people squatting the domain once it has been released so it's sad, but cannot be helped.

In terms of maintenance, it's not exactly true - I have not stopped maintaining the project. I agree there has been very little dev on it lately, but that's because there are very few requests for changes.
