### ISSUE TITLE
Outputting XML with Spark

### ISSUE THREAD

**Issue by maxtoroq** [SparkViewEngine/spark#61]
Can Spark output XML, e.g. using an `XmlWriter` ?

**Comment by RobertTheGrey** [comment]
Not sure exactly what you mean? Technically it already outputs XML by outputting HTML, but maybe I'm misunderstanding your need. Can you describe the use case a bit more so I can give a clearer answer?

**Comment by maxtoroq** [comment]
Razor introduced automatic encoding to avoid having to call `Html.Encode(foo)` or `Html.AttributeEncode(foo)` and instead just do `@foo`. I'm sure Spark does the same. But HTML and XML encoding are different. Is it customizable?

I guess the other obvious question is, how do you distinguish between Spark code, e.g. `<content>`, `<viewdata>`, `<if>`, and output? I'm guessing you cannot use Spark to output Spark, or any other markup language where names might conflict.

**Comment by RobertTheGrey** [comment]
I'm sorry @maxtoroq, somehow my GitHub notifications have all turned off and I didn't see this one. I've turned them back on now, so should see future messages.

Regarding encoding, yes it can be automatic and "always on", but as far as I know it's HTML centric, rather than XML. The current version of Spark ties directly into MVC HtmlHelper class to call `Encode` so it's not currently customizable but I'm working on porting to .NET Core which should hopefully abstract that to an interface where you could supply your own implementation.

For `<tags>` Spark does have it's own dialect that it looks for when parsing the AST, but if you wrap something inside `<ignore>` tags, then it just outputs the contents and does not attempt to parse it. Is that the kind of functionality you are looking for?

**Comment by RobertTheGrey** [comment]
@maxtoroq - if you're just looking to Transform XML with a Spark Template, then take a look at this example to see if it meets your needs: https://github.com/SparkViewEngine/spark/tree/master/src/Xpark
